; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool on Tue Oct 09 2018 13:27:56 GMT+0300
G91               ; relative positioning
G1 Z5 F6000 S2    ; lift Z relative to current position
G1 S1 Y355 F6000 ; move quickly to Y axis endstop and stop there (first pass)
G1 Y-5 F3000       ; go back a few mm
G1 S1 Y355 F360  ; move slowly to Y axis endstop once more (second pass)
G1 Z-5 F1000 S2   ; lower Z again
G90               ; absolute positioning